name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 custom_components/xiaozhi_mcp --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test with pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests/ -v --tb=short

  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
